@host =http://localhost:4000
###############
# Auth routes #
###############
POST {{host}}/auth/companies
###
POST  {{host}}/auth/singup
content-type: application/json

{
    "nombre":"ludis",
	"correo":"adminLud@gmail.com",
	"password":"ludis",
	"compañia":"611587c20f55fef5d479822e"
}
###
POST  {{host}}/auth/login
content-type: application/json

{
   "correo":"adminLud@gmail.com",
	"password":"ludis"
}
##############
# Api routes #
##############
@jwt =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTdkMTlmNzM4N2JiNzIxN2YwNmUwNSIsIm5vbWJyZSI6Ikx1ZCIsImNvbSI6IjYxMTViMzhiMjE1ZGRhOGRhYWI4Njc3OCIsImlhdCI6MTYyOTAzNTQ2OSwiZXhwIjoxNjI5MDkzMDY5fQ.iy5JkUL7e6v76tP3giDPJXwGCluxYI0ud2nA893ZzoA
###Tickets routes
###
GET  {{host}}/api
Authorization: Bearer {{jwt}}

###
POST {{host}}/api/tickets
Authorization: Bearer {{jwt}}
content-type: application/json

{
	# "hdUsuario":"6115dda32b1305fdddb723ba"
}
###
POST  {{host}}/api/tickets/6115b38b215dda8daab86778
Authorization: Bearer {{jwt}}
###
POST  {{host}}/api/ticket
content-type: application/json
Authorization: Bearer {{jwt}}

{
	"titulo":"PeraDesings funcionalidades",
	"descripcion":"Desarrollo de las funcionalidades del programa de diseño para el perapod",
	"estado":"activos",
	"hdUsuario":"6115c8872ddef5c5b6bcfe6d"
}
###
DELETE  {{host}}/api/ticket
content-type: application/json
Authorization: Bearer {{jwt}}

{
	"id":"6115f95d31ce745ee48dd8df"
}
###
PUT  {{host}}/api/ticket
content-type: application/json
Authorization: Bearer {{jwt}}

{
	 "id": "6115df59e4b2c005ccebeba9",
    "titulo": "Rastreador animal",
    "descripcion": "Implementacion en el gps del guacual donde va el animal con el servidor de entreagas",
    "estado": "activos"
}
###HDUsers routes
###
POST {{host}}/api/hdusers
content-type: application/json
Authorization: Bearer {{jwt}}

{

}
###
POST  {{host}}/api/hduser
content-type: application/json
Authorization: Bearer {{jwt}}

{
	"titulo":"Integracion del microprocesador .L1 en el perapot",
	"descripcion":"Necesito una perapot tan potente como su peramat con procesasdor .L1",
	"compañia":"6115b38b215dda8daab86778"
}
###
DELETE  {{host}}/api/hduser
content-type: application/json
Authorization: Bearer {{jwt}}

{
	"id":"611938458bd860acabbc270f"
}
###
PUT  {{host}}/api/hduser
content-type: application/json
Authorization: Bearer {{jwt}}

{
	"id":"6116746e36ca272429ae1bb8",
	"titulo":"Integracion .L1 en perapot",
	"descripcion":"Necesito una perapot tan potente como su peramat con procesasdor .L1",
	"estado":"En Proceso"
}